### ISSUE TITLE
User Story 6 – Database and Rating

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#10]
## Value proposition

As a user
I want to add and see the rating 
So that I can give my feedback on the activities and see the average rating the game receives.

## Description
<img width="538" alt="Screenshot 2023-08-18 at 16 17 34" src="https://github.com/izabelladobielewska/capstone-project/assets/137038301/b2ffed54-f75e-4d61-9e0f-d35b3ba509f0">

## Acceptance criteria

- [ ] The user can click on the stars (max 5 stars) to add their rating,
- [ ] the user can see the average rating a card has received,
- [ ] the rating data is stored in a database to ensure that it is available to users and applications that need to access it.

## Tasks

- [ ] create a new branch feature/add rating, 
- [ ] create a new component to give rating (stars),
- [ ] store the rating data in the database server, 
- [ ] GET and display the average rating of the card (i.e. create the logic to obtain the average).

## Size
L
