### ISSUE TITLE
User Story 7 – Add a Game

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#13]
## Value proposition

As a creative user
I want to get on option to "add a game"
To be able to contribute with my ideas.

## Description

The user can add a new game.

![Image](https://github.com/izabelladobielewska/capstone-project/assets/137038301/5fefa51d-b6e1-49be-ad44-84846a6e1162)

## Acceptance criteria

- [ ] in the main page there is an "Add a Game" button above the card deck;
- [ ] the button opens a form , where the user can add their game;
- [ ] the user has to fill in the **fields**: "Name", "What to prepare", "Wow to play", "Rules".
- [ ] In the form page the user can click the "Submit This Game" button;
- [ ] when clicked, the user is redirected to the game cards;
- [ ] if any of the entries is empty, the user will see an alert asking to fill out the field(s);.
- [ ] the new card is displayed as the first in the deck;
- [ ] after submitting the form the user is redirected to the deck, and the submit button resets the form.

## Tasks
- [ ] create a branch feat/add-a-game;
- [ ] create an icon / button / link that redirects to the form (Add a Game); 
- [ ] create a page for the form with the form component;
- [ ] create input fields with labels to add the information;
- [ ] create a Submit button ("Submit Your Game");
- [ ] write a handleSubmit function;
- [ ] create states for the game fields as an array of objects {id: UID(), gameName: "", rules: "", etc.};
- [ ] lift the states up to the `CardDeck` component.
- [ ] write a `handleCreateCard` function which receives the parameters uses them to set state variables.
- [ ] display the added information as new card;

## Size
L

**Comment by DorisW3** [comment]
Your user story is very good, but really huge. Maybe think about splitting it into tow parts, one for all input fields and the other for all checkboxes.

**Comment by izabelladobielewska** [comment]
Gosh, you're right! Thank you! :)
