### ISSUE TITLE
User Story 8 – Add checkboxes in the Game Form 

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#14]
## Value proposition

As a creative user
I want to tick the checkboxes for types of location, weather and company,
In order to specify the requirements to play my game.

## Description

The checkboxes are added at the end of the form.

![Screenshot 2023-08-24 at 13 18 24](https://github.com/izabelladobielewska/capstone-project/assets/137038301/3452cf82-9f68-4d87-bced-43bccd02d958)

## Acceptance criteria

- [ ] Button "add a new game" opens page, where the user can add their game;
- [ ] the page has a form and a headline "add your own game idea!";
- [ ] below the input fields, the user sees checkboxes: "The game is suitable for" (boat, city, mountains, forest), "Company": (alone, with a dog, 1person + me, more people"), "Weather": (rainy, windy, grey, sunny).
- [ ] when clicked, the user is redirected to the page with the game cards;
- [ ] the card is displayed at the first in the deck;
- [ ] if any of the boxes is unchecked, the user will see an alert asking to check the boxes.
- [ ] after submitting the form the user is redirected to the deck, and the submit button resets the form.

## Tasks

- [ ] create a new branch feat/form/add-checkboxes
- [ ] expand the form component: add the 3 questions (see above) with answer fields in form of checkboxes;
- [ ] create states for the game checkboxes values and add them to the array;
- [ ] lift the states up to the `CardDeck` component;
- [ ] add these these new keys (location, company and weather) to the new card.

## Size
S
