### ISSUE TITLE
User Story 9 – Add to Favorites

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#16]
## Value proposition

As a user
I want to add a play to my favourites
So that I can keep it for later.

## Description

![Screenshot 2023-08-28 at 09 12 11](https://github.com/izabelladobielewska/capstone-project/assets/137038301/49df78bc-7d6b-4918-8fa3-47d8ea171fcb)

## Acceptance criteria

- [ ] the user sees a favourite icon in the nav and on a card
- [ ] the user can click both icons
- [ ] clicking the icon in the nav brings the user to their favourite's page
- [ ] clicking the icon on the card saves the card in the favourites (the icon changes color)
- [ ] in the favourites page the user can see the selected card
- [ ] the user can click the icon on the card to unselected the card 
- [ ] clicking to remove from likes asks for confirmation "Do you want to remove the card from your favourites?"

## Tasks

- [ ]  create branch feat/addtofavorites
- [ ]  create a page with the function
- [ ] add the icon with the link to the navigation
- [ ] add the icon with the function to the card (research details)
 - [ ] use filter&map-method to render the pictures & usernames
 - [ ] research how to display only the cards which are “favorites” (ternary operator?)

## Size
L
