### ISSUE TITLE
US 10 – Edit Game

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#18]
## Value proposition

As a creative user
I want to see an option edit
In order to edit my games

## Description

![Screenshot 2023-08-30 at 09 25 14](https://github.com/izabelladobielewska/capstone-project/assets/137038301/abe736d1-cfde-48db-9e36-f5b5f2030aab)

## Acceptance criteria

- [ ] the user can click the edit icon on the cards they created
- [ ] the user can change all the fields
- [ ] upon clicking the "confirm changes" button the user sees an alert "Are you happy with the changes?"

## Tasks

- [ ] create a feature branch edit-card
- [ ] create the button component with the function that allows to edit the cards 
- [ ] limit the access only to the cards with the ids of the cards created by that user (IDs stored locally?)(research this part a bit)
- [ ] pre-fill the card with the value of the fields

## Size
M

**Comment by F-Kirchhoff** [comment]
LGTM
