### ISSUE TITLE
US11 – Load the changed/ created card first

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#20]
## Value proposition

As a user
I want to land in the preview of the card I just edited
In order to make sure I made no mistake

## Description
 
![Screenshot 2023-09-01 at 16 08 13](https://github.com/izabelladobielewska/capstone-project/assets/137038301/3db357b7-f913-47d1-abe2-740920ca0380)

## Acceptance criteria

- [ ] after editing the card user can click "confirm my changes"
- [ ] after clicking that button, the user lands in the preview of the card

## Tasks

- [ ] create a branch feat/edit-card/preview
- [ ] the button "confirm changes" ( apart from submitting the changes to the DB (previous US))
   redirects the user to the card with the id of the card they have just edited

## Size
S

**Comment by alperkuertuel** [comment]
Possibly you want to work with the next.js-Router to navigate your through the desired pages. Is that true? If so I recommend to take this in your tasks. All in all it looks good for this package.
