### ISSUE TITLE
US 12 – Change the checkboxes to tiles and split the form into two pages

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#21]
## Value proposition

As a user
I want to see tiles instead of checkboxes
In order to have a more pleasant experience of create a game.

## Description

![Screenshot 2023-09-01 at 16 28 40](https://github.com/izabelladobielewska/capstone-project/assets/137038301/00b7110a-2cea-4ca3-b05a-399b6dab39e4)

## Acceptance criteria

- [ ] the user clicks on "add a new game" icon and is redirected to a form, where:
- [ ] they should see the textfields, and
- [ ] buttons (previously checkboxes)
- [ ] a clicked button changes appearance from outline to filled

## Tasks

- [ ] create a new branch edit/add-game/checkboxes-to-buttons
- [ ] in the form (page: add-game) change the input from checkbox to button (like in filtering feature where I also have buttons that filter)
- [ ] create a button with an onclick setStep(0) and setStep(1)
- [ ] split the game into 2 sections
- [ ] style the buttons

## Size
M

**Comment by chris-kuehn** [comment]
LGTM :)
