### ISSUE TITLE
US 13 – Refine the UI in the Preferences Page

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#23]
## Value proposition

As a user
I want the aesthetics to be consistent
In order to feel familiar with the page

### Refine the UI in the Preferences Page. 
![Screenshot 2023-09-04 at 12 15 08](https://github.com/izabelladobielewska/capstone-project/assets/137038301/783834b0-31de-43dd-ab3e-01c57b957cec)

## Acceptance criteria

- [ ] The user sees a header: Set your preferencesM
- [ ] the submit button is fixed to the bottom of the page;
- [ ] the selection boxes have consistent size and width, are displayed in two rows;
- [ ] a clicked box changes color;
- [ ] the user can unclick the box to remove the filter.

## Tasks

- [ ] open new branch css/preferences page;
- [ ] change the styling of the tiles;
- [ ] change the styling of the "submit" button.

## Size
XS
