### ISSUE TITLE
US14 Refinement in the Favourite's Page

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#24]
## Value proposition

As a user
I want to be informed about the page's I have clicked
In order to understand my options

## Description

Put the info text in the favorites page.

![Screenshot 2023-09-04 at 12 26 03](https://github.com/izabelladobielewska/capstone-project/assets/137038301/dc5ce4df-22be-4a66-90e8-4b3f1240b67c)

## Acceptance criteria

- [ ] upon clicking the heart in the nav, the user can review their liked cards;
- [ ] the favourite's page has a header "Here are your favourites" or "You have no favorites yet, browse the games to find some."
- [ ] the text at the bottom of the card is not "XX matching games" but " XX games"
## Tasks

- [ ] Open a new branch "favs/conditional-text;
- [ ] the page with favorites is a filter, and not a page, so I will place a conditional text if the likedGames is less than zero

**Comment by DorisW3** [comment]
Hi Izabella,
I don't understand the last acceptance criteria. Therefore, I am confused about the part "if the likedGames is _less than zero_" in tasks. Why _less_?🙈

**Comment by izabelladobielewska** [comment]
Hi, i wrote less than zero, because the condition should be that if you have 0 likes then it should display a different text. Now i see that it should actually be "less or equal" <= 🤪 
My User Stories are getting more and more hectic, i think im very tired  😵‍💫
