### ISSUE TITLE
US 15  – Delete Button

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#25]
## Value proposition

As a user
I want to have a delete option
In order to be able to remove my games.

## Description

<img width="513" alt="Screenshot 2023-09-06 at 11 11 58" src="https://github.com/izabelladobielewska/capstone-project/assets/137038301/110a83d3-8be2-47a4-9aa4-6e43c4abc4e4">

## Acceptance criteria

- [ ] the user sees an active delete button (greyed out)  if it is a card he created
- [ ] the delete button removes the card from the deck and displays the next card in the deck 
- [ ] before final delete the user sees and alert "Irretrievably delete this game?"
- [ ] the user sees an inactive button if it isn't his card

## Tasks

- [ ] create a feat/delete-button branch
- [ ] add a button delete
- [ ] add an onclick handleDelete that removes the card with the current id
- [ ] figure out how to remove it from the database
- [ ] add an alert to the handleDelete "Irretrievably delete this game?"

## Size
M

**Comment by milodevhh** [comment]
Hey Izabella, that fits well. I think it's great that you include the last crud operation.  Please make sure that there is a dialog if you really want to delete the game / the entry.

**Comment by izabelladobielewska** [comment]
Good Point!! will add
