### ISSUE TITLE
User Story 1 - Endstagram

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#3]
## Value proposition

As a bored user
I want to receive game suggestions
So that I can skim through them and choose an activity.

## Description

Display the deck of cards with the games.
<img width="195" alt="Screenshot 2023-08-13 at 15 53 26" src="https://github.com/izabelladobielewska/capstone-project/assets/137038301/e4a5c392-edce-494f-99f1-da94ff6c9284">

## Acceptance criteria

- [x] The page has a name “Endstagram”.
- [x] Game cards are displayed one by one.
- [x] Each card displays the name of the game, information on what to prepare, how to play, the rules.
- [x] Button "next" displays the next game.
- [x] Button "previous" displays the previous game.

## Tasks

- [x] Create a new branch "display all cards".
- [x] Create an array of the first 10-15 games.
- [x] Build the page.
- [x] Create a header element with h1 "Endstagram".
- [x] Create a card component.
- [x] Write a function that that creates a card for each object in the array "Games".
- [x] Implement two buttons below the card: "Previous" and  "Next" - the buttons display the next or the previous game.

## Size
L

**Comment by DorisW3** [comment]
Hey Izabella,
I like your user story  very much! In my opinion it is really good 🫶🏼. Maybe think about splitting the story into one for creating the array of games und the other for everything else, so that it is a little smaller. 
P.s I really like the name  :-D
