### ISSUE TITLE
User Story 2 – Endstagram

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#4]
## Value proposition

As a user
I want to be able to choose between different answers
 In order to receive suggestions for suitable activities later on.

## Description

By clicking the "Preferences" icon the user lands in the Preferences page with the first question.

![Screenshot 2023-08-13 at 21 52 19](https://github.com/izabelladobielewska/capstone-project/assets/137038301/b04a9e72-bd7a-4578-b94c-d4aeb304a9a9)

## Acceptance criteria
- [ ] The page has a headline “Endstagram”.
- [ ]  the Preferences Icon is visible in the header.
- [ ]  Clicking on the Preferences Icon the user is redirected to the  page with the form.
- [ ]  The first question about the "location" is displayed. 
- [ ]  Possible answers are: I'm stuck in a boat, I'm in a forest, I'm in a city, I'm in the mountains.

## Tasks

- [ ] Create new branch "Feature/form-location"
- [ ] Build the Preferences Page
- [ ] Create a form component

## Size
S-M
