### ISSUE TITLE
User Story 3 – Endstagram

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#6]
## US 3 – Endstagram
As a user  
I want to be able to see the options for my whereabouts 
In order to receive matching suggestions later on.

## Description
By clicking on the "Show Matching Games" Button the user gets the games that match the criteria.
<img width="413" alt="Screenshot 2023-08-16 at 10 58 18" src="https://github.com/izabelladobielewska/capstone-project/assets/137038301/275ef378-48a7-4ed8-ad05-a9daf54f3031">

## Acceptance criteria
- [ ]   The page has a headline “Endstagram”. 
- [ ]  The question about the "location" is displayed ("I am bored, and ....")
- [ ]  Possible answers are: I'm stuck on a boat, I'm in a forest, I'm in a city, I'm in the mountains.
- [ ]  Multiple answers are possible.

## Tasks
- [ ]    Create new branch "Feature/form-filter-button"
- [ ]    Create a button component with the logic that filters the displayed card objects
Size
S-M

**Comment by MiejkeHoltermann** [comment]
Cool idea! I would maybe try and split the second task into two or three tasks, like 1. create a button, 2. ... Do you already have a property in your array which specifies which game is suitable for which location?

**Comment by izabelladobielewska** [comment]
Hi Miejke, thank you! :) The splitting is probably a good idea, I actually did the first step as a user story 2:) Now i would add the button to show the results according to the filter, and yes, I do have a key "location" :)

**Comment by jonas8900** [comment]
Looks good to me ! For the next time i would maybe add more Details to your Tasks so you have a better help when you get stucked! But thats only a helpful think for me :)!
