### ISSUE TITLE
User Story 4 – Endstagram

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#8]
## Value proposition

As a user
I want to see more filters
In order to be able to get fitting game suggestions later on.

## Description

<img width="223" alt="Screenshot 2023-08-17 at 10 48 57" src="https://github.com/izabelladobielewska/capstone-project/assets/137038301/7bc85639-b3a7-4216-9ccd-64a95771951e">

## Acceptance criteria

- [ ] in the preferences page the user sees a question regarding the weather: "the weather is:" with 4 possible answers "rainy", "cloudy", "windy", "sunny".
- [ ] User sees a question regarding the weather "my company:" with 4 answers: "just me", "me + 1", "dog", "more people".
- [ ] Multiple answers are possible.
- [ ] The buttons select the criteria.
- [ ] The button "Show Matching Games" shows filtered games.

## Tasks

- [ ] Create a new branch feature/form-weather-and-company,
- [ ] In the preferences page add category "the weather is" (h3) with 4 answer button components below,
- [ ] add h3 "company" category and 4 answer button components below.

## Size
M

**Comment by NicoleHoerner** [comment]
Looks good! Go ahead!
