### ISSUE TITLE
User Story 5

### ISSUE THREAD

**Issue by izabelladobielewska** [izabelladobielewska/capstone-project#9]
## Value proposition

As a user
I want to get more information
In order to to see what are my preferences and how many games match my criteria.

## Description
<img width="319" alt="Us5" src="https://github.com/izabelladobielewska/capstone-project/assets/137038301/9ab7c36e-3c76-409f-9d3e-72478bfb9b78">

## Acceptance criteria

- [x] The user sees the information text "**Congrats**, turns there are actually some analog activities for you. Here are some ideas  for you: ",
- [x] the user sees the selected preferences, if there are any specified,
- [x] the user sees how many games match their criteria.

## Tasks

- [x] create a new branch "feature/information-around-the-game",
- [x] add a section with an h3 and a p element,
- [x] add and element for the selected preferences, at this point it can be a list or chips
- [x] display the number of objects that fit the criteria.
## Size
XS

**Comment by DorisW3** [comment]
looks fine :-)
